version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    # environment:
    #   - DATABASE_URL=postgres://user:password@db:5432/mydb
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    volumes:
      - ./json:/app/json

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: english_app_2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/create-topics.sh:/usr/bin/create-topics.sh
    # entrypoint:
    #   [
    #     "/bin/sh",
    #     "-c",
    #     "/usr/bin/create-topics.sh && /etc/confluent/docker/run",
    #   ]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  db_data:
