# version: "3.8"

# services:
#   app:
#     build:
#        context: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#       - kafka
#     env_file:
#       - .env
#     volumes:
#       - .:/app:ro  # Volume diatur hanya-baca
#   #   networks:
#   #     - internal

#   db:
#     image: postgres:15.3
#     environment:
#       POSTGRES_USER: learnlingo
#       POSTGRES_PASSWORD: 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
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
# #    networks:
# #     - internal
# #    user: "999"  # Non-root user untuk PostgreSQL

#   kafka:
#     image: confluentinc/cp-kafka:7.5.0
#     ports:
#       - "9093:9093"
#       - "9092:9092"
#   # Hanya expose port external yang diperlukan
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#     depends_on:
#       - zookeeper
#     volumes:
#       - kafka_data:/var/lib/kafka/data
#    # networks:
#    #   - internal
#      # Non-root user

#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.5.0
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     volumes:
#       - zookeeper_data:/var/lib/zookeeper
#   #  networks:
#    #   - internal
#     # Non-root user

# volumes:
#   db_data:
#   kafka_data:
#   zookeeper_data:

# #networks:
#  # internal:
#   #  driver: bridge
# #


version: "3.8"

services:
  # app:
  #   build:
  #      context: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - kafka
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app:ro  # Volume diatur hanya-baca
  # #   networks:
  # #     - internal

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: learnlingo
      POSTGRES_PASSWORD: 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
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    networks:
#     - internal
#    user: "999"  # Non-root user untuk PostgreSQL

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9093:9093"
      - "9092:9092"
  # Hanya expose port external yang diperlukan
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
   # networks:
   #   - internal
     # Non-root user

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper



volumes:
  db_data:
  kafka_data:
  zookeeper_data:

#networks:
 # internal:
  #  driver: bridge
#